apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: trading-bot
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: trading-bot
  template:
    metadata:
      labels:
        app: trading-bot
      annotations:
         vault.hashicorp.com/agent-inject: "true"
         vault.hashicorp.com/role: "trading-bot"
        
        # Alpaca Trading Bot Credentials
         vault.hashicorp.com/agent-inject-secret-alpaca-credentials: "kv/data/secret/trading-bot/alpaca-paper-credentials"
         vault.hashicorp.com/agent-inject-template-alpaca-credentials: |
           {{`{{- with secret "kv/data/secret/trading-bot/alpaca-paper-credentials" -}}`}}
           KEY={{`{{ .Data.data.key }}`}}
           SECRET={{`{{ .Data.data.secret }}`}}
           {{`{{- end }}`}}

         restartedAt: "{{ now | date "2006-01-02T15:04:05Z07:00" }}"
    spec:
      serviceAccountName: trading-bot
      automountServiceAccountToken: true
      containers:
        - name: trading-bot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: BASH_ENV
              value: /vault/secrets/config
{{- if .Values.nodeSelector }}
    nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}