apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: quanthelm-30k
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: quanthelm-30k
  template:
    metadata:
      labels:
        app: quanthelm-30k
      annotations:
         vault.hashicorp.com/agent-inject: "true"
         vault.hashicorp.com/role: "trading-bot"
        
         # Alpaca Trading Bot Credentials
         vault.hashicorp.com/agent-inject-secret-alpaca-credentials: "kv/data/secret/trading-bot/quanthelm-30k/alpaca-paper-credentials"
         vault.hashicorp.com/agent-inject-template-alpaca-credentials: |
           {{`{{- with secret "kv/data/secret/trading-bot/quanthelm-30k/alpaca-paper-credentials" -}}`}}
           KEY={{`{{ .Data.data.key }}`}}
           SECRET={{`{{ .Data.data.secret }}`}}
           {{`{{- end }}`}}

         # OpenAI Credentials
         vault.hashicorp.com/agent-inject-secret-openai-credentials: "kv/data/secret/trading-bot/openai-token"
         vault.hashicorp.com/agent-inject-template-openai-credentials: |
            {{`{{- with secret "kv/data/secret/trading-bot/openai-token" -}}`}}
            TOKEN={{`{{ .Data.data.token }}`}}
            {{`{{- end }}`}}

         # Mailgun Credentials
         vault.hashicorp.com/agent-inject-secret-mailgun-credentials: "kv/data/secret/trading-bot/mailgun-token"
         vault.hashicorp.com/agent-inject-template-mailgun-credentials: |
            {{`{{- with secret "kv/data/secret/trading-bot/mailgun-token" -}}`}}
            TOKEN={{`{{ .Data.data.token }}`}}
            {{`{{- end }}`}}

         restartedAt: "{{ now | date "2006-01-02T15:04:05Z07:00" }}"
    spec:
      serviceAccountName: trading-bot
      automountServiceAccountToken: true
      containers:
        - name: quanthelm-30k
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: BASH_ENV
              value: /vault/secrets/config
            - name: RUN_SWING_TRADE_SCORER
              value: "false"
            - name: APP_NAME
              value: {{ .Chart.Name | quote }}
            - name: APP_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
{{- if .Values.nodeSelector }}
    nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}