apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: {{ .Values.mongodb.name }}
spec:
  members: {{ .Values.mongodb.members }}
  type: ReplicaSet
  version: {{ .Values.mongodb.version }}
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: {{ .Values.mongodb.user.name }}
      db: {{ .Values.mongodb.user.db }}
      passwordSecretRef:
        name: {{ .Values.mongodb.user.passwordSecret }}
      roles:
        {{- range .Values.mongodb.roles }}
        - name: {{ .name }}
          db: {{ .db }}
        {{- end }}
      scramCredentialsSecretName: {{ .Values.mongodb.user.scramSecret }}
  additionalMongodConfig:
    {{- toYaml .Values.mongodb.additionalMongodConfig | nindent 4 }}
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongod
              ports:
                - containerPort: 27017
                  name: mongo
                  protocol: TCP
