apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api
    spec:
      {{- include "prowler.nodeAffinity" . | nindent 6 }}
      initContainers:
        - name: set-ulimits
          image: busybox
          command: ["sh", "-c", "ulimit -n 65535"]
          securityContext:
            privileged: true
        - name: wait-for-postgres
          image: busybox
          command: ["sh", "-c", "until nc -z {{ .Release.Name }}-postgres {{ .Values.postgres.port }}; do echo waiting for postgres; sleep 2; done"]
        - name: wait-for-valkey
          image: busybox
          command: ["sh", "-c", "until nc -z {{ .Release.Name }}-valkey {{ .Values.valkey.port }}; do echo waiting for valkey; sleep 2; done"]
        - name: wait-for-neo4j
          image: busybox
          command: ["sh", "-c", "until nc -z {{ .Release.Name }}-neo4j {{ .Values.neo4j.port }}; do echo waiting for neo4j; sleep 2; done"]
      containers:
        - name: api
          image: "{{ .Values.api.image }}:{{ .Values.api.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.port }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-env
            - secretRef:
                name: {{ .Values.existingSecret }}
          command: ["/home/prowler/docker-entrypoint.sh", "prod"]
          securityContext:
            capabilities:
              add: ["SYS_RESOURCE"]
            runAsNonRoot: false
          volumeMounts:
            - name: config
              mountPath: /home/prowler/.config/prowler-api
              subPath: prowler/api/config
            - name: output
              mountPath: /tmp/prowler_api_output
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | quote }}
        - name: output
          emptyDir: {}
