apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-valkey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-valkey
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-valkey
    spec:
      {{- include "prowler.nodeAffinity" . | nindent 6 }}
      containers:
        - name: valkey
          image: "{{ .Values.valkey.image }}:{{ .Values.valkey.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.valkey.port }}
          readinessProbe:
            exec:
              command: ["valkey-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: prowler/valkey
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | quote }}
