{{- if .Values.wazuh.enabled }}
{{- $components := list "ui" "worker" "worker-beat" "mcp" }}
{{- range $component := $components }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-{{ $component }}-wazuh-agent-config
data:
  ossec.conf: |
    <ossec_config>
      <client>
        <server>
          <address>{{ $.Values.wazuh.manager }}</address>
          <port>1514</port>
          <protocol>tcp</protocol>
        </server>
        <config-profile>kubernetes,prowler-{{ $component }}</config-profile>
        <enrollment>
          <agent_name>{{ $.Release.Name }}-{{ $component }}</agent_name>
          <groups>{{ $.Values.wazuh.group | default "kubernetes" }}</groups>
        </enrollment>
      </client>

      <localfile>
        <log_format>syslog</log_format>
        <location>/shared-logs/{{ $component }}.log</location>
      </localfile>
    </ossec_config>
---
{{- end }}
{{- end }}
