mongodb:
  name: mongodb
  version: "6.0.5"
  members: 2
  user:
    name: damien
    db: admin
    password: "itainteasy"
    passwordSecret: notthesame
    scramSecret: mongodb-scram-secret
  roles:
    - name: clusterAdmin
      db: damien
    - name: userAdmin
      db: damien
  additionalMongodConfig:
    storage:
      wiredTiger:
        engineConfig:
          journalCompressor: zlib

service:
  type: ClusterIP
  port: 27017
  targetPort: 27017

ingress:
  className: nginx
  enabled: true
  host: mongodb.dsb-hub.local
  annotations:
    cert-manager.io/cluster-issuer: mkcert-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  tls:
    enabled: true
    host: mongodb.dsb-hub.local  
    secretName: mongodb-cert-tls