apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-wazuh-agent-config
data:
  ossec.conf: |
    <ossec_config>
      <client>
        <server>
          <address>{{ .Values.wazuh.manager }}</address>
          <port>1514</port>
          <protocol>tcp</protocol>
        </server>
        <config-profile>kubernetes,uptime-kuma</config-profile>
      </client>

      <localfile>
        <log_format>syslog</log_format>
        <location>/shared-logs/uptime-kuma.log</location>
      </localfile>
    </ossec_config>