replicaCount: 1

image:
  repository: yukisan1225/trading-bot
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  className: nginx
  enabled: true
  host: paper-trader.dsb-hub.local
  annotations:
    cert-manager.io/cluster-issuer: mkcert-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  tls:
    enabled: true
    host: paper-trader.dsb-hub.local  
    secretName: paper-trader-cert-tls

resources: {}