apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "signal-api.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "signal-api.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "signal-api.name" . }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
      containers:
        - name: signal-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: MODE
              value: "{{ .Values.env.MODE }}"
          volumeMounts:
            - name: signal-data
              mountPath: /home/.local/share/signal-cli
      volumes:
        - name: signal-data
          {{- if .Values.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
          {{- else }}
          emptyDir: {}
          {{- end }}
