replicaCount: 1

image:
  repository: bbernhard/signal-cli-rest-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  className: nginx
  enabled: true
  host: signalapi.dsb-hub.local
  annotations:
    cert-manager.io/cluster-issuer: mkcert-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  tls:
    enabled: true
    host: signalapi.dsb-hub.local  
    secretName: signalapi-cert-tls

persistence:
  enabled: true
  existingClaim: ""
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi

env:
  MODE: native
