replicaCount: 2

image:
  repository: cloudflare/cloudflared
  tag: latest
  pullPolicy: Always

tunnel:
  secretName: cloudflare-tunnel-token
  secretKey: token
  logLevel: info
  metricsAddress: "0.0.0.0:2000"

livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 1

wazuh:
  enabled: true
  manager: 10.0.0.22
  group: k8s
  agentImage: wazuh/wazuh-agent:4.7.5
  persistence:
    storageClass: microk8s-hostpath
    size: 5Gi
