apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /opt/sonarqube/data /opt/sonarqube/logs /opt/sonarqube/extensions"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: sonarqube-data
              mountPath: /opt/sonarqube/data
              subPath: sonarqube/data
            - name: sonarqube-data
              mountPath: /opt/sonarqube/logs
              subPath: sonarqube/logs
            - name: sonarqube-data
              mountPath: /opt/sonarqube/extensions
              subPath: sonarqube/extensions
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: sonarqube
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: SONAR_JDBC_URL
              value: "jdbc:postgresql://{{ .Release.Name }}-postgres:{{ .Values.postgresql.service.port }}/{{ .Values.postgresql.database }}"
            - name: SONAR_JDBC_USERNAME
              value: {{ .Values.postgresql.username | quote }}
            - name: SONAR_JDBC_PASSWORD
              value: {{ .Values.postgresql.password | quote }}
          volumeMounts:
            - name: sonarqube-data
              mountPath: /opt/sonarqube/data
              subPath: sonarqube/data
            - name: sonarqube-data
              mountPath: /opt/sonarqube/logs
              subPath: sonarqube/logs
            - name: sonarqube-data
              mountPath: /opt/sonarqube/extensions
              subPath: sonarqube/extensions
      volumes:
        - name: sonarqube-data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.sonarqube.existingClaim | quote }}
